--- #YAML:1.0
name:               TRD-Watch-Web
version:            0.0.4
abstract:           [One line description of module's purpose here]
author:
    - Takuya Ichikawa <ichi@cpan.org>
license:            unknown
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Test::More:          0
    Test::Perl::Critic:  0
    Time::HiRes:         0
    TRD::DebugLog:       0
    version:             0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
